### ISSUE TITLE
Test DNS error on GrapheneSGX-Golang

### ISSUE THREAD

**Issue by hustliyilin** [intel/GrapheneSGX-Golang-Support-and-Enhancement#4]
I write a simple golang program to test DNS and this is my [repository](https://github.com/hustliyilin/DNS-test.git). My repository includes DNS-test.go, Makefile, manifest.template, and rm.sh(`rm *.sig *.token *.sgx` manually). I test my DNS-test.go in both native(`./DNS-test`) and graphene-sgx-golang (`SGX=1 ./pal_loader DNS-test.manifest.sgx`)modes. In the native mode, DNS-test can work(tranfer a  domain name to its IP). However, in the graphene-sgx-golang mode, DNS-test can't work. Could  you help me? Thanks a lot.

**Comment by AI-Memory** [comment]
@hustliyilin I have tried your test source code, it shows the futex wait endlessly.
is it the same symptom as your result. if not, could you show us error messages ? Thanks.

**Comment by hustliyilin** [comment]
OK，my test result is not the same as your. And these are my results in two modes(graphene-sgx and native mode). In the graphene-sgx mode(`SGX=1 ./pal_loader DNS_test.manifest.sgx`), the result is 

```
[urts 27212] sgx_main.c:799:load_enclave exec_uri: "file:chaincode_Lite"
[urts 27212] sgx_main.c:234:initialize_enclave loading "/root/gopath/GrapheneSGX-Golang-Support-and-Enhancement/Pal/src/../../Runtime/libpal-Linux-SGX.so"
 
ctx = context.Background.WithDeadline(2019-09-11 01:47:50.082686 +0000 UTC m=+1.518584001 [999.34ms]) 
network = tcp 
address = github.com:443 
dialContext error!
```
and in the native mode(`./DNS_test`) , the result is 
 
```
ctx = context.Background.WithDeadline(2019-09-11 01:48:06.568019727 +0000 UTC m=+1.000325579 [999.947065ms]) 
network = tcp 
address = github.com:443 
```

**Comment by hustliyilin** [comment]
> 
> 
> @hustliyilin I have tried your test source code, it shows the futex wait endlessly.
> is it the same symptom as your result. if not, could you show us error messages ? Thanks.

Yes，OK，my test result is a little different from your. And these are my results in two modes(graphene-sgx and native mode). In the graphene-sgx mode(`SGX=1 ./pal_loader DNS-test.manifest.sgx`), it shows the futex wait endlessly,but there are some logs, the logs are

```
[urts 27212] sgx_main.c:799:load_enclave exec_uri: "file:DNS-test"
[urts 27212] sgx_main.c:234:initialize_enclave loading "/root/gopath/GrapheneSGX-Golang-Support-and-Enhancement/Pal/src/../../Runtime/libpal-Linux-SGX.so"
 
ctx = context.Background.WithDeadline(2019-09-11 01:47:50.082686 +0000 UTC m=+1.518584001 [999.34ms]) 
network = tcp 
address = github.com:443 
dialContext error!
```
and in the native mode(`./DNS-test`) , it can successfully run and end, the logs are 
 
```
ctx = context.Background.WithDeadline(2019-09-11 01:48:06.568019727 +0000 UTC m=+1.000325579 [999.947065ms]) 
network = tcp 
address = github.com:443 
```

**Comment by AI-Memory** [comment]
Thanks for more info about this issue.  
I have tried not to rely on the DNS service by replacing the address with "127.0.0.1:22" and
removing the invocation of "context.WithTimeout(...)" using context.Background() instead. but it still failed. so could you also try this and print out the value of "err" in the code and attaching the log file using the following command ? 
SGX=1 ./pal_loader DNS-test.manifest.sgx | tee log.txt

**Comment by hustliyilin** [comment]
OK，I updated DNS-test.go and printed out the value of the "err" in the code of DNS-test.go (the address is "www.github.com:443"), and this is my logs. It seems the  domain name is tranferred to a IPv6 address, so the connection refused. 

```
# SGX=1 ./pal_loader DNS-test.manifest.sgx 
[urts 55274] sgx_main.c:799:load_enclave exec_uri: "file:DNS-test"
[urts 55274] sgx_main.c:234:initialize_enclave loading "/root/gopath/GrapheneSGX-Golang-Support-and-Enhancement/Pal/src/../../Runtime/libpal-Linux-SGX.so"
ctx = context.Background.WithDeadline(2019-09-12 01:07:53.458365 +0000 UTC m=+1.524575001 [999.469ms]) 
network = tcp 
address = www.github.com:443 
err = dial tcp: lookup www.github.com on [::1]:53: dial udp [::1]:53: connect: connection refused 
dialContext error!
```
and in native mode, I think the domain name is tranferred to a IPv4 address, so it can work successfully. 

What's more, I will try not to rely on the DNS service by replacing the address with "127.0.0.1:22" and
removing the invocation of "context.WithTimeout(...)" using context.Background(). And I will give
 you my logs as soon as possible!

**Comment by hustliyilin** [comment]
I updated my DNS-test [repository](https://github.com/hustliyilin/DNS-test/blob/master/DNS-test.go). This time I revised the value of address and ctx. The new values of address and ctx are "127.0.0.1:22" and context.Background() respectively. What's more, I used the command in graphene-sgx-golang mode(`SGX=1 ./pal_loader DNS-test.manifest.sgx | tee log.txt` ) and this is my [log.txt](https://github.com/hustliyilin/DNS-test/blob/master/log.txt), the result shows it can work successfully in the graphene-sgx-golang mode. Thanks for your advice.
